from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('home/', views.home_view, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('insumos/', views.supplies_view, name='insumos'),
    path('insumos/data/<int:insumo_id>/', views.get_insumo_data, name='get_insumo_data'),
    path('productos/data/<int:producto_id>/', views.get_producto_data, name='get_producto_data'),
    path('productos/', views.product_view, name='productos'),
    path('proveedores/', views.proveedor_view, name='proveedores'),
    path('proveedores/data/<int:proveedor_id>/', views.get_proveedor_data, name='get_proveedor_data'),
    path('proveedores/eliminar/<int:proveedor_id>/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('compras/', views.compras_view, name='compras'),
    path('clientes/', views.cliente_view, name='clientes'),
    path('clientes/data/<int:cliente_id>/', views.get_cliente_data, name='get_cliente_data'),
    path('clientes/eliminar/<int:cliente_id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('manualistas/', views.manualista_view, name='manualistas'),
    path('manualistas/data/<int:manualista_id>/', views.get_manualista_data, name='get_manualista_data'),
    path('manualistas/eliminar/<int:manualista_id>/', views.eliminar_manualista, name='eliminar_manualista'),
    path('produccion/', views.produccion_view, name='produccion'),
    path('produccion/guardar/', views.produccion_view, name='guardar_produccion'),
    path('produccion/calcular/', views.calcular_produccion, name='calcular_produccion'),
    path('seguimiento-produccion/', views.seguimiento_produccion_view, name='seguimiento_produccion'),
    path('seguimiento-produccion/<int:produccion_id>/fabricante/', views.orden_fabricante_view, name='orden_fabricante'),
    path('ventas/', views.ventas_view, name='ventas'),
    path('seguimiento-ventas/', views.seguimiento_ventas_view, name='seguimiento_ventas'),
    path('pagos-manualistas/', views.pagos_manualistas_view, name='pagos_manualistas'),
    path('pagos-manualistas/<int:manualista_id>/', views.pagos_manualista_detalle_view, name='pagos_manualista_detalle'),
    path('informes/', views.informes_view, name='informes'),
    path('informes/pdf/', views.informes_pdf_view, name='informes_pdf'),
    path('importar-exportar/', views.importar_exportar_view, name='importar_exportar'),
    path('importar-exportar/exportar/', views.export_csv_view, name='export_csv'),
]
