# Generated by Django 4.2.17 on 2025-01-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boton',
        ),
    ]
