# Generated by Django 4.2.5 on 2025-01-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0004_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
