# Generated by Django 4.2.5 on 2025-01-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0005_nombre_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='insumos/')),
                ('colores', models.ManyToManyField(to='app_alejandra.color')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.medida')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.nombre')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.referencia')),
            ],
        ),
    ]
