# Generated by Django 4.2.5 on 2025-01-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0006_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='imagen',
        ),
        migrations.AddField(
            model_name='insumo',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
