# Generated by Django 4.2.5 on 2025-02-02 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0007_remove_insumo_imagen_insumo_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('referencia', models.CharField(max_length=500, null=True, unique=True)),
                ('nombre', models.CharField(max_length=500, null=True)),
                ('colores', models.ManyToManyField(to='app_alejandra.color')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.medida')),
            ],
        ),
    ]
