# Generated by Django 4.2.5 on 2025-02-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0008_insumo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('colores', models.ManyToManyField(to='app_alejandra.color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.producto')),
            ],
        ),
    ]
