# Generated by Django 4.2.5 on 2025-02-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0009_producto_productoinsumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.insumo2'),
        ),
    ]
