# Generated by Django 4.2.5 on 2025-02-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0013_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.insumo')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.medida')),
            ],
        ),
    ]
