# Generated by Django 4.2.5 on 2025-02-03 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0014_compra_comprainsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprainsumo',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.color'),
        ),
        migrations.AddField(
            model_name='comprainsumo',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
