# Generated by Django 4.2.5 on 2025-02-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0015_comprainsumo_color_comprainsumo_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprainsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.insumo2'),
        ),
    ]
