# Generated by Django 4.2.5 on 2025-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0018_manualista'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualista',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
