# Generated by Django 4.2.5 on 2025-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0019_manualista_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualista',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='manualista',
            name='dia_nacimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualista',
            name='mes_nacimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
