# Generated by Django 4.2.5 on 2025-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0021_remove_manualista_dia_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='manualista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
