# Generated by Django 4.2.5 on 2025-02-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0022_alter_cliente_email_alter_manualista_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_tentativa', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado')], default='Pendiente', max_length=20)),
                ('manualista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.manualista')),
            ],
        ),
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.color')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='app_alejandra.produccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.producto')),
            ],
        ),
    ]
