# Generated by Django 4.2.5 on 2025-03-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0023_produccion_lineaproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_por_paquete',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_paquete',
            field=models.BooleanField(default=False),
        ),
    ]
