# Generated by Django 4.2.5 on 2025-03-29 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0024_producto_cantidad_por_paquete_producto_es_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinsumo',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.color'),
        ),
    ]
