# Generated by Django 4.2.5 on 2025-04-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0025_productoinsumo_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('En producción', 'En producción'), ('Terminado', 'Terminado'), ('Vendido', 'Vendido')], default='En producción', max_length=20)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.producto')),
            ],
        ),
    ]
