# Generated by Django 4.2.5 on 2025-04-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0026_inventarioproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprainsumo',
            name='estado',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Reserva Producción', 'Reserva Producción')], default='Compra', max_length=30),
        ),
    ]
