# Generated by Django 4.2.5 on 2025-04-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0027_comprainsumo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprainsumo',
            name='produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.produccion'),
        ),
        migrations.AlterField(
            model_name='comprainsumo',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.compra'),
        ),
        migrations.AlterField(
            model_name='comprainsumo',
            name='estado',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Reserva Producción', 'Reserva Producción'), ('Cancelado', 'Cancelado'), ('Terminado', 'Terminado')], default='Compra', max_length=30),
        ),
    ]
