# Generated by Django 4.2.5 on 2025-04-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0028_comprainsumo_produccion_alter_comprainsumo_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprainsumo',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
