# Generated by Django 4.2.5 on 2025-04-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0029_alter_comprainsumo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproducto',
            name='produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.produccion'),
        ),
    ]
