# Generated by Django 4.2.5 on 2025-10-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0031_inventarioproducto_valor_venta_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, help_text='Persona responsable/contacto directo', max_length=200, null=True),
        ),
    ]
