# Generated by Django 4.2.5 on 2025-10-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0033_alter_cliente_documento_alter_cliente_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualista',
            name='documento',
            field=models.CharField(blank=True, help_text='Opcional - puede quedar vacío', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manualista',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'Número de Identificación Tributaria'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte'), ('SIN', 'Sin Documento')], default='CC', max_length=3),
        ),
    ]
