# Generated by Django 4.2.5 on 2025-10-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0034_alter_manualista_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaproduccion',
            name='cantidad_entregada',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad ya entregada por el manualista'),
        ),
        migrations.CreateModel(
            name='EntregaParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.PositiveIntegerField()),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la entrega', null=True)),
                ('linea_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_parciales', to='app_alejandra.lineaproduccion')),
            ],
        ),
    ]
