# Generated by Django 4.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0035_lineaproduccion_cantidad_entregada_entregaparcial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_despachada', models.PositiveIntegerField(default=0)),
                ('valor_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='app_alejandra.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DespachoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('linea_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='app_alejandra.lineaventa')),
            ],
        ),
    ]
