# Generated by Django 4.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0036_lineaventa_despachoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='valor_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Monto acordado a pagar al manualista por esta orden', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PagoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app_alejandra.produccion')),
            ],
        ),
    ]
