# Generated by Django 4.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0037_produccion_valor_a_pagar_pagoproduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('envio_extra', 'Se envían más insumos'), ('sobrante', 'Sobran insumos')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.color')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.insumo2')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_insumos', to='app_alejandra.produccion')),
            ],
        ),
    ]
