# Generated by Django 4.2.5

from django.db import migrations, models


def backfill_numeros(apps, schema_editor):
    Compra = apps.get_model('app_alejandra', 'Compra')
    Produccion = apps.get_model('app_alejandra', 'Produccion')
    Venta = apps.get_model('app_alejandra', 'Venta')
    for i, compra in enumerate(Compra.objects.order_by('id'), start=1):
        compra.numero = f"CO-{i:04d}"
        compra.save(update_fields=['numero'])
    for i, prod in enumerate(Produccion.objects.order_by('id'), start=1):
        prod.numero = f"PR-{i:04d}"
        prod.save(update_fields=['numero'])
    for i, venta in enumerate(Venta.objects.order_by('id'), start=1):
        venta.numero = f"FA-{i:04d}"
        venta.save(update_fields=['numero'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_alejandra', '0038_ajusteinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='numero',
            field=models.CharField(blank=True, help_text='Ej: CO-0001', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='numero',
            field=models.CharField(blank=True, help_text='Ej: PR-0001', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero',
            field=models.CharField(blank=True, help_text='Ej: FA-0001', max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_numeros, noop),
    ]
